# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScreenCalibrationUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScreenCal_UI(object):
    def setupUi(self, ScreenCal_UI):
        ScreenCal_UI.setObjectName("ScreenCal_UI")
        ScreenCal_UI.resize(240, 320)
        ScreenCal_UI.setMaximumSize(QtCore.QSize(240, 320))
        ScreenCal_UI.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.TL_Btn = QtWidgets.QPushButton(ScreenCal_UI)
        self.TL_Btn.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.TL_Btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/Close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TL_Btn.setIcon(icon)
        self.TL_Btn.setIconSize(QtCore.QSize(20, 20))
        self.TL_Btn.setObjectName("TL_Btn")
        self.TR_Btn = QtWidgets.QPushButton(ScreenCal_UI)
        self.TR_Btn.setGeometry(QtCore.QRect(200, 150, 40, 40))
        self.TR_Btn.setText("")
        self.TR_Btn.setIcon(icon)
        self.TR_Btn.setIconSize(QtCore.QSize(20, 20))
        self.TR_Btn.setObjectName("TR_Btn")
        self.BL_Btn = QtWidgets.QPushButton(ScreenCal_UI)
        self.BL_Btn.setGeometry(QtCore.QRect(0, 280, 40, 40))
        self.BL_Btn.setText("")
        self.BL_Btn.setIcon(icon)
        self.BL_Btn.setIconSize(QtCore.QSize(20, 20))
        self.BL_Btn.setObjectName("BL_Btn")
        self.X_Val = QtWidgets.QLCDNumber(ScreenCal_UI)
        self.X_Val.setGeometry(QtCore.QRect(70, 40, 81, 31))
        self.X_Val.setFrameShadow(QtWidgets.QFrame.Raised)
        self.X_Val.setDigitCount(8)
        self.X_Val.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.X_Val.setObjectName("X_Val")
        self.Y_Val = QtWidgets.QLCDNumber(ScreenCal_UI)
        self.Y_Val.setGeometry(QtCore.QRect(70, 80, 81, 31))
        self.Y_Val.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Y_Val.setDigitCount(8)
        self.Y_Val.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Y_Val.setObjectName("Y_Val")
        self.X_Val_txt = QtWidgets.QLabel(ScreenCal_UI)
        self.X_Val_txt.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.X_Val_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.X_Val_txt.setObjectName("X_Val_txt")
        self.Y_Val_txt = QtWidgets.QLabel(ScreenCal_UI)
        self.Y_Val_txt.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.Y_Val_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Y_Val_txt.setObjectName("Y_Val_txt")
        self.PenUpDown = QtWidgets.QLabel(ScreenCal_UI)
        self.PenUpDown.setGeometry(QtCore.QRect(20, 180, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PenUpDown.setFont(font)
        self.PenUpDown.setAlignment(QtCore.Qt.AlignCenter)
        self.PenUpDown.setObjectName("PenUpDown")
        self.Step_1 = QtWidgets.QLabel(ScreenCal_UI)
        self.Step_1.setGeometry(QtCore.QRect(40, 10, 81, 16))
        self.Step_1.setObjectName("Step_1")
        self.Step_2 = QtWidgets.QLabel(ScreenCal_UI)
        self.Step_2.setGeometry(QtCore.QRect(40, 290, 81, 16))
        self.Step_2.setObjectName("Step_2")
        self.Step_3 = QtWidgets.QLabel(ScreenCal_UI)
        self.Step_3.setGeometry(QtCore.QRect(120, 160, 81, 16))
        self.Step_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Step_3.setObjectName("Step_3")
        self.Y_Val_2 = QtWidgets.QLCDNumber(ScreenCal_UI)
        self.Y_Val_2.setGeometry(QtCore.QRect(70, 120, 81, 31))
        self.Y_Val_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Y_Val_2.setDigitCount(8)
        self.Y_Val_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Y_Val_2.setObjectName("Y_Val_2")
        self.Z_Val_txt = QtWidgets.QLabel(ScreenCal_UI)
        self.Z_Val_txt.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.Z_Val_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Z_Val_txt.setObjectName("Z_Val_txt")

        self.retranslateUi(ScreenCal_UI)
        QtCore.QMetaObject.connectSlotsByName(ScreenCal_UI)

    def retranslateUi(self, ScreenCal_UI):
        _translate = QtCore.QCoreApplication.translate
        ScreenCal_UI.setWindowTitle(_translate("ScreenCal_UI", "Form"))
        self.X_Val_txt.setText(_translate("ScreenCal_UI", "X Value:"))
        self.Y_Val_txt.setText(_translate("ScreenCal_UI", "Y Value:"))
        self.PenUpDown.setText(_translate("ScreenCal_UI", "Pen Up"))
        self.Step_1.setText(_translate("ScreenCal_UI", "< Touch HERE!"))
        self.Step_2.setText(_translate("ScreenCal_UI", "< Touch HERE!"))
        self.Step_3.setText(_translate("ScreenCal_UI", "Touch HERE! >"))
        self.Z_Val_txt.setText(_translate("ScreenCal_UI", "Z Value:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScreenCal_UI = QtWidgets.QWidget()
    ui = Ui_ScreenCal_UI()
    ui.setupUi(ScreenCal_UI)
    ScreenCal_UI.show()
    sys.exit(app.exec_())
